### ISSUE TITLE
first middle last (fml)

### ISSUE THREAD

**Issue by hoolymama** [ConductorTechnologies/cioseq#9]
FML should behave similarly to the existing subsample() method, the difference being that the first and last elements of the result are the first and last of the sequence, and the remaining elements are distributed with even gaps.

Example: A sequence from 1-100
Current algorithm: 4 subsamples yields [13,38,63,88]
New FML algorithm: 4 subsamples should yield [1,34,67,100]

Eventually, all submitters will use fml scout frames by default. For example, the scout frames attribute can be `fml:4`
Alternatively, we could just leave it at auto:4 and replace the behavior with the fml algorithm. Thoughts?
 

For example, you could add a key

**Comment by aibrahim-cw** [comment]
Hi, feature is complete. Code has been tested and pushed to this branch:
https://github.com/ConductorTechnologies/cioseq/tree/issue-09-fml-aei

**Comment by aibrahim-cw** [comment]
>Alternatively, we could just leave it at auto:4 and replace the behavior with the fml algorithm. Thoughts?
My opinion is to make "fml:3" the default. But it depends on what customers prefer.

**Comment by aibrahim-cw** [comment]
Should this code be merged with Master?

**Comment by aibrahim-cw** [comment]
Related update:
https://github.com/ConductorTechnologies/ciohoudini/compare/testing-aei

**Comment by aibrahim-cw** [comment]
Hi, updates to the FML and test cases are here:
https://github.com/ConductorTechnologies/cioseq/tree/issue-09-fml-aei

**Comment by aibrahim-cw** [comment]
Made another update to FML:
https://github.com/ConductorTechnologies/cioseq/tree/issue-09-fml-aei
